import MainTopics from '../../components/MainTopics'
import ProfileHeader from '../../components/ProfileHeader'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container mx-auto xl:px-6'>
          <div className='mb-8'>
            <ProfileHeader/>
            <MainTopics/>
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
